# Generated by Django 5.0 on 2026-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raumnummer', models.CharField(max_length=20, unique=True, verbose_name='Raumnummer')),
                ('raumname', models.CharField(max_length=100, verbose_name='Raumname')),
                ('raumtyp', models.CharField(choices=[('einzelzimmer', 'Einzelzimmer'), ('doppelzimmer', 'Doppelzimmer'), ('suite', 'Suite'), ('konferenzraum', 'Konferenzraum')], max_length=20, verbose_name='Raumtyp')),
                ('kapazitaet', models.PositiveIntegerField(verbose_name='Kapazität')),
                ('preis_pro_nacht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis pro Nacht')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ['raumnummer'],
            },
        ),
    ]
