# Generated by Django 5.0 on 2026-01-05 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=20, unique=True, verbose_name='Rechnungsnummer')),
                ('rechnungsdatum', models.DateField(verbose_name='Rechnungsdatum')),
                ('faelligkeitsdatum', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('versendet', 'Versendet'), ('bezahlt', 'Bezahlt'), ('storniert', 'Storniert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('mwst_satz', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='MwSt.-Satz (%)')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('buchung', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rechnung', to='bookings.booking', verbose_name='Buchung')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-rechnungsdatum'],
            },
        ),
    ]
