# Generated by Django 5.0 on 2026-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers')], max_length=10, verbose_name='Anrede')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('stadt', models.CharField(max_length=100, verbose_name='Stadt')),
                ('land', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['nachname', 'vorname'],
            },
        ),
    ]
