# Generated by Django 5.0 on 2026-01-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check-in')),
                ('check_out', models.DateField(verbose_name='Check-out')),
                ('anzahl_gaeste', models.PositiveIntegerField(verbose_name='Anzahl Gäste')),
                ('status', models.CharField(choices=[('ausstehend', 'Ausstehend'), ('bestaetigt', 'Bestätigt'), ('storniert', 'Storniert'), ('abgeschlossen', 'Abgeschlossen')], default='ausstehend', max_length=20, verbose_name='Status')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='customers.customer', verbose_name='Kunde')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='rooms.room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-check_in'],
            },
        ),
    ]
